spring:
  application:
    name: userservice
  sql:
    init:
      mode: never
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/userdb}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        format_sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
jwt:
  secret: mysupersecretkeymysupersecretkey88888888
keycloak:
  server-url: http://localhost:9090
  realm: myrealm
  client-id: myclient
  client-secret: mysecret
  redirect-uri: http://localhost:8080/auth/oidc-callback
  grant-type: authorization_code
